<?php
require_once '_bootstrap.php';
$selectedId=(int)($_REQUEST['competency_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=$_POST['action']??'';
    if($action==='save_competency'){
      $id=(int)$_POST['id'];$name=trim($_POST['name']??'');if($name==='')throw new RuntimeException('กรุณาระบุชื่อสมรรถนะ');
      if($id)$pdo->prepare('UPDATE competencies SET name=?,description=?,type=?,order_seq=? WHERE id=?')->execute([$name,trim($_POST['description']??''),$_POST['type'],(int)$_POST['order_seq'],$id]);
      else{$pdo->prepare('INSERT INTO competencies(name,description,type,order_seq) VALUES (?,?,?,?)')->execute([$name,trim($_POST['description']??''),$_POST['type'],(int)$_POST['order_seq']]);$id=(int)$pdo->lastInsertId();}
      adminRedirect('competencies.php?competency_id='.$id,'success','บันทึกข้อมูลสมรรถนะเรียบร้อย');
    }
    if($action==='save_level'){
      $pdo->prepare('INSERT INTO competency_levels(competency_id,expected_level,level_description) VALUES (?,?,?) ON DUPLICATE KEY UPDATE level_description=VALUES(level_description)')->execute([(int)$_POST['competency_id'],(int)$_POST['expected_level'],trim($_POST['level_description'])]);
      adminRedirect('competencies.php?competency_id='.(int)$_POST['competency_id'],'success','บันทึกคำอธิบายระดับเรียบร้อย');
    }
    if($action==='save_indicator'){
      $id=(int)$_POST['id'];$comp=(int)$_POST['competency_id'];$position=(int)($_POST['position_id']??0)?:null;$text=trim($_POST['indicator_text']??'');if($text==='')throw new RuntimeException('กรุณาระบุพฤติกรรมบ่งชี้');
      if($id)$pdo->prepare('UPDATE indicators SET expected_level=?,position_id=?,indicator_text=?,order_seq=? WHERE id=?')->execute([(int)$_POST['expected_level'],$position,$text,(int)$_POST['order_seq'],$id]);
      else $pdo->prepare('INSERT INTO indicators(competency_id,expected_level,position_id,indicator_text,order_seq) VALUES (?,?,?,?,?)')->execute([$comp,(int)$_POST['expected_level'],$position,$text,(int)$_POST['order_seq']]);
      adminRedirect('competencies.php?competency_id='.$comp,'success','บันทึกพฤติกรรมบ่งชี้เรียบร้อย');
    }
    if($action==='delete_indicator'){
      $id=(int)$_POST['id'];$comp=(int)$_POST['competency_id'];
      $stmt=$pdo->prepare('SELECT COUNT(*) FROM evaluation_scores WHERE indicator_id=?');$stmt->execute([$id]);if($stmt->fetchColumn())throw new RuntimeException('พฤติกรรมนี้มีคะแนนประเมินแล้ว จึงไม่สามารถลบได้');
      $pdo->prepare('DELETE FROM indicators WHERE id=?')->execute([$id]);adminRedirect('competencies.php?competency_id='.$comp,'success','ลบพฤติกรรมบ่งชี้เรียบร้อย');
    }
  }catch(Throwable $e){adminRedirect('competencies.php'.($selectedId?'?competency_id='.$selectedId:''),'error',$e->getMessage());}
}
$competencies=$pdo->query('SELECT c.*,COUNT(DISTINCT i.id) indicator_count FROM competencies c LEFT JOIN indicators i ON i.competency_id=c.id GROUP BY c.id ORDER BY c.type,c.order_seq,c.id')->fetchAll();
if(!$selectedId&&$competencies)$selectedId=(int)$competencies[0]['id'];
$current=null;foreach($competencies as $c)if((int)$c['id']===$selectedId)$current=$c;
$levels=[];$indicators=[];if($current){$s=$pdo->prepare('SELECT * FROM competency_levels WHERE competency_id=? ORDER BY expected_level');$s->execute([$selectedId]);$levels=$s->fetchAll();$s=$pdo->prepare('SELECT i.*,p.name position_name FROM indicators i LEFT JOIN positions p ON p.id=i.position_id WHERE i.competency_id=? ORDER BY i.expected_level,i.order_seq,i.id');$s->execute([$selectedId]);$indicators=$s->fetchAll();}
$positions=$pdo->query('SELECT * FROM positions ORDER BY name')->fetchAll();
require_once '../includes/header.php';adminPageHeader(appIcon('clipboard-list') . ' สมรรถนะและพฤติกรรมบ่งชี้','จัดการชื่อสมรรถนะ คำอธิบายระดับ และรายการพฤติกรรมที่ใช้ให้คะแนน');renderAdminFlash();
?>
<div class="admin-split-layout" style="display:grid;grid-template-columns:minmax(280px,34%) 1fr;gap:1rem;align-items:start"><div class="card"><h3>รายการสมรรถนะ</h3><?php foreach($competencies as $c): ?><a href="?competency_id=<?= $c['id'] ?>" style="display:block;padding:.7rem;border-bottom:1px solid var(--border-color);text-decoration:none;color:inherit;background:<?= $selectedId==$c['id']?'var(--primary-50)':'transparent' ?>"><strong><?= htmlspecialchars($c['name']) ?></strong><br><small><?= $c['type']==='core'?'สมรรถนะหลัก':'สมรรถนะเฉพาะ' ?> · <?= $c['indicator_count'] ?> พฤติกรรม</small></a><?php endforeach ?><hr><h4>เพิ่มสมรรถนะ</h4><form method="post" class="admin-stack-form"><input type="hidden" name="action" value="save_competency"><input type="hidden" name="id" value="0"><input class="form-control" type="text" name="name" placeholder="ชื่อสมรรถนะ" required><select class="form-control" name="type"><option value="core">สมรรถนะหลัก</option><option value="functional">สมรรถนะเฉพาะ</option></select><input class="form-control" type="number" name="order_seq" value="1"><textarea class="form-control" name="description" placeholder="คำอธิบาย"></textarea><button class="btn btn-primary">เพิ่มสมรรถนะ</button></form></div>
<?php if($current): ?><div><div class="card" style="margin-bottom:1rem"><h3>แก้ไขสมรรถนะ</h3><form method="post" class="admin-stack-form"><input type="hidden" name="action" value="save_competency"><input type="hidden" name="id" value="<?= $current['id'] ?>"><label>ชื่อ</label><input class="form-control" type="text" name="name" value="<?= htmlspecialchars($current['name']) ?>" required><label>ประเภท</label><select class="form-control" name="type"><option value="core" <?= $current['type']==='core'?'selected':'' ?>>สมรรถนะหลัก</option><option value="functional" <?= $current['type']==='functional'?'selected':'' ?>>สมรรถนะเฉพาะ</option></select><label>ลำดับ</label><input class="form-control" type="number" name="order_seq" value="<?= $current['order_seq'] ?>"><label>ความหมาย</label><textarea class="form-control" name="description" rows="4"><?= htmlspecialchars($current['description']??'') ?></textarea><button class="btn btn-primary">บันทึก</button></form></div>
<div class="card" style="margin-bottom:1rem"><h3>คำอธิบายระดับ</h3><?php $levelMap=[];foreach($levels as $l)$levelMap[$l['expected_level']]=$l['level_description'];for($i=1;$i<=3;$i++): ?><form method="post" style="margin-bottom:.8rem"><input type="hidden" name="action" value="save_level"><input type="hidden" name="competency_id" value="<?= $selectedId ?>"><input type="hidden" name="expected_level" value="<?= $i ?>"><label>ระดับ <?= $i ?></label><textarea class="form-control" name="level_description" required><?= htmlspecialchars($levelMap[$i]??'') ?></textarea><button class="btn btn-secondary">บันทึกระดับ <?= $i ?></button></form><?php endfor ?></div>
<div class="card"><h3>พฤติกรรมบ่งชี้</h3>
<form method="post" class="admin-indicator-form" style="padding:1rem;background:var(--primary-50);margin-bottom:1rem"><input type="hidden" name="action" value="save_indicator"><input type="hidden" name="id" value="0"><input type="hidden" name="competency_id" value="<?= $selectedId ?>"><div class="admin-indicator-grid" style="display:grid;grid-template-columns:120px 1fr 100px;gap:.5rem"><select class="form-control" name="expected_level"><?php for($i=1;$i<=3;$i++): ?><option value="<?= $i ?>">ระดับ <?= $i ?></option><?php endfor ?></select><select class="form-control" name="position_id"><option value="0">ใช้ทุกตำแหน่ง</option><?php foreach($positions as $p): ?><option value="<?= $p['id'] ?>"><?= htmlspecialchars($p['name']) ?></option><?php endforeach ?></select><input class="form-control" type="number" name="order_seq" value="1"></div><textarea class="form-control" name="indicator_text" placeholder="ข้อความพฤติกรรมบ่งชี้" required></textarea><button class="btn btn-primary">เพิ่มพฤติกรรม</button></form>
<?php foreach($indicators as $i): ?><div style="padding:.8rem;border-bottom:1px solid var(--border-color)"><form method="post" class="admin-indicator-form"><input type="hidden" name="action" value="save_indicator"><input type="hidden" name="id" value="<?= $i['id'] ?>"><input type="hidden" name="competency_id" value="<?= $selectedId ?>"><div class="admin-indicator-grid" style="display:grid;grid-template-columns:120px 1fr 100px;gap:.5rem"><select class="form-control" name="expected_level"><?php for($n=1;$n<=3;$n++): ?><option value="<?= $n ?>" <?= $i['expected_level']==$n?'selected':'' ?>>ระดับ <?= $n ?></option><?php endfor ?></select><select class="form-control" name="position_id"><option value="0">ใช้ทุกตำแหน่ง</option><?php foreach($positions as $p): ?><option value="<?= $p['id'] ?>" <?= $i['position_id']==$p['id']?'selected':'' ?>><?= htmlspecialchars($p['name']) ?></option><?php endforeach ?></select><input class="form-control" type="number" name="order_seq" value="<?= $i['order_seq'] ?>"></div><textarea class="form-control" name="indicator_text" required><?= htmlspecialchars($i['indicator_text']) ?></textarea><button class="btn btn-secondary">บันทึกการแก้ไข</button></form><form method="post" style="display:inline" onsubmit="return confirm('ยืนยันการลบ?')"><input type="hidden" name="action" value="delete_indicator"><input type="hidden" name="id" value="<?= $i['id'] ?>"><input type="hidden" name="competency_id" value="<?= $selectedId ?>"><button class="btn btn-danger">ลบ</button></form></div><?php endforeach ?></div></div><?php endif ?></div>
<?php require_once '../includes/footer.php'; ?>
